spring:
  config:
    import:
      - optional:dotenv:.env
      - optional:classpath:parametric-filters.yml
      - optional:classpath:murata-categories.yml
      - optional:classpath:vendors.yml
      - optional:classpath:scraper.yml

openai:
  api:
    key: ${OPENAI_API_KEY}
    base-url: https://api.openai.com/v1
    default-model: ${OPENAI_MODEL:gpt-3.5-turbo}

resilience4j:
  retry:
    instances:
      openaiApi:
        max-attempts: 3        # try up to 3 times
        wait-duration: 500ms   # 0.5s between attempts
        retry-exceptions:
          - org.springframework.web.client.HttpClientErrorException
          - org.springframework.web.client.ResourceAccessException

logging:
  level:
    root: INFO
    org.springframework.cache: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"
